name: Deploy Django Project Directly

on:
  push:
    branches: [ main ]  # 当代码推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当有拉取请求合并到 main 分支时触发

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t django-web-app .
    
    - name: Export Docker Image as Tarball
      run: |
        docker save -o web-app.tar django-web-app

    - name: Upload Docker Image Tarball as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-app-tar
        path: web-app.tar

    - name: Download Docker Image Tarball from Artifact
      uses: actions/download-artifact@v3
      with:
        name: web-app-tar
        path: .

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SERVER_PASSWORD }}
        port: 22
        envs: SERVER_HOST,SERVER_USERNAME,SERVER_PASSWORD
        script: |
          # 如果需要的话，创建存储目录
          mkdir -p  opt/web-app
          # 复制 tarball 到远程服务器
          cp web-app.tar opt/web-app
          # 加载 Docker 镜像
          docker load -i opt/web-app/web-app.tar
          # 停止现有容器
          docker stop web-app || true
          # 删除现有容器
          docker rm web-app || true
          # 删除悬挂的镜像
          docker rmi $(docker images -f "dangling=true" -q) || true
          # 运行新的容器
          docker run -d --name web-app -p 8000:8000 django-web-app
